export enum ContractType {
  COLLECTOR = 'collector',
  FACTORY = 'factory',
  GOV = 'gov',
  LIMIT_ORDER = 'limitOrder',
  MINT = 'mint',
  ORACLE = 'oracle',
  STAKING = 'staking',
  TOKEN = 'token',
  LP_TOKEN = 'lpToken',
  TOKEN_FACTORY = 'tokenFactory',
  PAIR = 'pair',
  COMMUNITY = 'community',
  AIRDROP = 'airdrop',
  COLLATERAL_ORACLE = 'collateralOracle',
  LOCK = 'lock',
}
