export enum TxType {
  BUY = 'BUY',
  SELL = 'SELL',

  SEND = 'SEND',
  RECEIVE = 'RECEIVE',
  SWAP = 'SWAP',

  OPEN_POSITION = 'OPEN_POSITION',
  DEPOSIT_COLLATERAL = 'DEPOSIT_COLLATERAL',
  WITHDRAW_COLLATERAL = 'WITHDRAW_COLLATERAL',
  MINT = 'MINT',

  PROVIDE_LIQUIDITY = 'PROVIDE_LIQUIDITY',
  WITHDRAW_LIQUIDITY = 'WITHDRAW_LIQUIDITY',
  STAKE = 'STAKE',
  UNSTAKE = 'UNSTAKE',
  WITHDRAW_REWARDS = 'WITHDRAW_REWARDS',  
}
